version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: egy-discovery-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      
      # N8N Configuration
      - N8N_BASE_URL=http://localhost:5678
      - N8N_API_KEY=${N8N_API_KEY:-}
      - N8N_TIMEOUT_SECONDS=30
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=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
      - OPENAI_MODEL=gpt-3.5-turbo
      - OPENAI_MAX_TOKENS=1000
      - OPENAI_TEMPERATURE=-0.7
      
      # Database Configuration (for future use)
      - DATABASE_URL=${DATABASE_URL:-sqlite:///egy_discovery.db}
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379}
      
      # Security Configuration
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-change-in-production}
      
      # External Services
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID:-}
      - SENTRY_DSN=${SENTRY_DSN:-}
      
      # Feature Flags
      - ENABLE_AI_AGENTS=true
      - ENABLE_N8N_WORKFLOWS=true
      - ENABLE_WEB_SCRAPING=true
      
    restart: unless-stopped
    volumes:
      # Mount workflows directory for easy updates
      - ./server/workflows:/app/server/workflows:ro
      # Mount logs directory
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
 